# Python Programming Basic Assignment-8

In [1]:
import numpy as np

#### 1. Write a Python Program to Add two Matrices ?

In [9]:
def Add_two_matrices():
    l1 = eval(input("enter the array 1 : "))
    l2 = eval(input("enter the array 2 : "))
    mat1 = np.array(l1)
    mat2 = np.array(l2)
    result = mat1+mat2
    print(result)
Add_two_matrices()

enter the array 1 : [[1,2,4,5],[3,4,5,6]]
enter the array 2 : [[3,6,7,8],[2,3,5,7]]
[[ 4  8 11 13]
 [ 5  7 10 13]]


#### 2. Write a Python Program to Multiply two Matrices ?

In [12]:
def Mult_two_matrices():
    l1 = eval(input("enter the array 1 : "))
    l2 = eval(input("enter the array 2 : "))
    mat1 = np.array(l1)
    mat2 = np.array(l2)
    result = mat1.dot(mat2)
    print(result)
Mult_two_matrices()

enter the array 1 : [[1,2,4,5],[3,4,5,6]]
enter the array 2 : [[3,6],[7,8],[2,3],[5,7]]
[[ 50  69]
 [ 77 107]]


#### 3. Write a Python Program to transpose a Matrix ?

In [14]:
def Transpose_matrix():
    l1 = eval(input("enter the array 1 : "))

    mat1 = np.array(l1)
    result = mat1.transpose()
    print(result)
Transpose_matrix()

enter the array 1 : [[2,3,45,5],[2,3,4,5],[1,2,33,5]]
[[ 2  2  1]
 [ 3  3  2]
 [45  4 33]
 [ 5  5  5]]


#### 4. Write a Python Program to sort Words in an Alphabatical Order ?

In [21]:
def sortString():
    in_string = sorted(input("Enter the String :").title().split())
    print(' '.join(in_string))

sortString()

Enter the String :My name is Afaf Ahmed
Afaf Ahmed Is My Name


#### 5. Write a Python Program to remove Punctuations From a String ?

In [22]:
def removePunctuatuions():
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    in_string = input('Enter a String: ')
    out_string = ''
    for ele in in_string:
        if ele not in punctuations:
            out_string += ele
    print(out_string)
    
removePunctuatuions()

Enter a String: Ohh# my Godd!!
Ohh my Godd
